package inc.guessourfriend;

import android.content.Intent;
import android.media.Image;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;

import java.util.List;

public class EndOfGameController extends AppCompatActivity {

    private Game game;
    private User opponentUser;
    // These four variables below will be generated by the variables above
    //      when we get to integration testing
    private Friend winner;
    private Friend loser;
    // The two mystery friends below will be of type "MutualFriend"
    //      when we get to integration testing
    private Friend myMysteryFriend;
    private Friend theirMysteryFriend;

    private FBProfileModel FBProfile;

    public void onDone(View view){
        Intent myIntent = new Intent(this, CurrentGamesController.class);
        startActivity(myIntent);
    }

    public void onRematch(View view){

    }

    private void displayForWinner(View view, FBProfileModel FBProfile){
        List<Friend> myFriendList = FBProfile.getFriendList();
        Friend friend = myFriendList.get(0);
        String profilePic = friend.getProfilePicture();
    }

    private void displayForLoser(View view){

    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_end_of_game_controller);
        FBProfile = DatabaseHelper.getFBProfile(this);
        //if(winner.getFacebookID())
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_end_of_game_controller, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
