package inc.guessourfriend;

import android.content.Intent;
import android.media.Image;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.TextView;

import com.facebook.FacebookSdk;
import com.facebook.login.widget.ProfilePictureView;

import java.util.List;

public class EndOfGameController extends SlideNavigationController {

    private Game game;
    private User opponentUser;
    // These four variables below will be generated by the variables above
    //      when we get to integration testing
    private long winner;
    private long loser;
    // The two mystery friends below will be of type "MutualFriend"
    //      when we get to integration testing
    private Friend myMysteryFriend;
    private Friend theirMysteryFriend;

    private FBProfileModel fbProfile;

    public void onDone(View view){
        // start the current games activity by using "openActivity(int position) - do it this way
        //      because it doesn't work as expected if you just make an intent and start an
        //      activity (this is the consequence of using the slide navigation controller)
        openActivity(3);
    }

    public void onRematch(View view){

    }

    private void displayForWinner(){
        List<Friend> myFriendList = fbProfile.getFriendList();
        Friend friend = myFriendList.get(0);
        String profilePic = friend.getProfilePicture();
        ProfilePictureView profilePictureView = (ProfilePictureView) findViewById(R.id.the_winning_guess);
        profilePictureView.setProfileId(Long.toString(friend.getFacebookID()));
        TextView guessedNameTextView = (TextView) findViewById(R.id.guessed_name);
        guessedNameTextView.setText(friend.getFullName());
    }

    private void displayForLoser(){

    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getLayoutInflater().inflate(R.layout.activity_end_of_game_controller, frameLayout);
        //mDrawerList.setItemChecked(position, true);
        //setTitle(listArray[position]);

        fbProfile = DatabaseHelper.getFBProfile(this);
        // Simulating a loss
        //winner = fbProfile.getFriendList().get(1).getFacebookID();
        //loser = fbProfile.getFacebookID();
        // Simulating a win
        winner = fbProfile.getFacebookID();
        loser = fbProfile.getFriendList().get(1).getFacebookID();
        if(winner == fbProfile.getFacebookID()){
            // this user is the winner
            displayForWinner();
        }else{
            displayForLoser();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_end_of_game_controller, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
